///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Demo01
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Demo01Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("85a9b8b5-1060-4c63-9559-006fa89127cd")]
    public partial class Demo01Repository : RepoGenBaseFolder
    {
        static Demo01Repository instance = new Demo01Repository();
        Demo01RepositoryFolders.MotDePasseAppFolder _motdepasse;
        Demo01RepositoryFolders.SetupOCM9999991AppFolder _setupocm9999991;
        Demo01RepositoryFolders.SettingsOcm2AppFolder _settingsocm2;
        Demo01RepositoryFolders.ConfirmerAppFolder _confirmer;

        /// <summary>
        /// Gets the singleton class instance representing the Demo01Repository element repository.
        /// </summary>
        [RepositoryFolder("85a9b8b5-1060-4c63-9559-006fa89127cd")]
        public static Demo01Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Demo01Repository() 
            : base("Demo01Repository", "/", null, 0, false, "85a9b8b5-1060-4c63-9559-006fa89127cd", ".\\RepositoryImages\\Demo01Repository85a9b8b5.rximgres")
        {
            _motdepasse = new Demo01RepositoryFolders.MotDePasseAppFolder(this);
            _setupocm9999991 = new Demo01RepositoryFolders.SetupOCM9999991AppFolder(this);
            _settingsocm2 = new Demo01RepositoryFolders.SettingsOcm2AppFolder(this);
            _confirmer = new Demo01RepositoryFolders.ConfirmerAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("85a9b8b5-1060-4c63-9559-006fa89127cd")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The MotDePasse folder.
        /// </summary>
        [RepositoryFolder("ccddfcfe-bbaf-42c1-af73-e1438a3e2019")]
        public virtual Demo01RepositoryFolders.MotDePasseAppFolder MotDePasse
        {
            get { return _motdepasse; }
        }

        /// <summary>
        /// The SetupOCM9999991 folder.
        /// </summary>
        [RepositoryFolder("0360fde7-5bea-4de0-a1fd-d0bf9bf32d36")]
        public virtual Demo01RepositoryFolders.SetupOCM9999991AppFolder SetupOCM9999991
        {
            get { return _setupocm9999991; }
        }

        /// <summary>
        /// The SettingsOcm2 folder.
        /// </summary>
        [RepositoryFolder("413a49aa-6c53-4413-9db1-89591d113649")]
        public virtual Demo01RepositoryFolders.SettingsOcm2AppFolder SettingsOcm2
        {
            get { return _settingsocm2; }
        }

        /// <summary>
        /// The Confirmer folder.
        /// </summary>
        [RepositoryFolder("565f90a0-7a69-4c4f-9839-43e45070cb92")]
        public virtual Demo01RepositoryFolders.ConfirmerAppFolder Confirmer
        {
            get { return _confirmer; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Demo01RepositoryFolders
    {
        /// <summary>
        /// The MotDePasseAppFolder folder.
        /// </summary>
        [RepositoryFolder("ccddfcfe-bbaf-42c1-af73-e1438a3e2019")]
        public partial class MotDePasseAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _passwordInfo;
            RepoItemInfo _buttonokInfo;

            /// <summary>
            /// Creates a new MotDePasse  folder.
            /// </summary>
            public MotDePasseAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MotDePasse", "/form[@name='GetPassword']", parentFolder, 30000, null, true, "ccddfcfe-bbaf-42c1-af73-e1438a3e2019", "")
            {
                _passwordInfo = new RepoItemInfo(this, "Password", "?/?/text[@name='Password']", "?/?/text[@name='Password']", 30000, null, "f849cd8d-af2d-442b-80f5-bf142ddc4a2d");
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "?/?/button[@name='Btn_OK']", "?/?/button[@name='Btn_OK']", 30000, null, "005371b6-3d60-4e2e-bffd-fb36e047f994");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ccddfcfe-bbaf-42c1-af73-e1438a3e2019")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ccddfcfe-bbaf-42c1-af73-e1438a3e2019")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("f849cd8d-af2d-442b-80f5-bf142ddc4a2d")]
            public virtual Ranorex.Text Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("f849cd8d-af2d-442b-80f5-bf142ddc4a2d")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("005371b6-3d60-4e2e-bffd-fb36e047f994")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("005371b6-3d60-4e2e-bffd-fb36e047f994")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }
        }

        /// <summary>
        /// The SetupOCM9999991AppFolder folder.
        /// </summary>
        [RepositoryFolder("0360fde7-5bea-4de0-a1fd-d0bf9bf32d36")]
        public partial class SetupOCM9999991AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonokInfo;
            RepoItemInfo _fermerInfo;

            /// <summary>
            /// Creates a new SetupOCM9999991  folder.
            /// </summary>
            public SetupOCM9999991AppFolder(RepoGenBaseFolder parentFolder) :
                    base("SetupOCM9999991", "/form[@name='MainForm']", parentFolder, 30000, null, true, "0360fde7-5bea-4de0-a1fd-d0bf9bf32d36", "")
            {
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "form[@name='CfgBmpPrn']/?/?/button[@name='OKBtn']", ".//button[@name='OKBtn']", 30000, null, "10ec2fad-752e-452b-b646-3add4ade5779");
                _fermerInfo = new RepoItemInfo(this, "Fermer", "form[@name='MccCfgDlg']/?/?/button[@name='btnOK']", ".//button[@name='btnOK']", 30000, null, "75816664-dbdc-469a-9066-48c9327fb5b8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("0360fde7-5bea-4de0-a1fd-d0bf9bf32d36")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0360fde7-5bea-4de0-a1fd-d0bf9bf32d36")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("10ec2fad-752e-452b-b646-3add4ade5779")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("10ec2fad-752e-452b-b646-3add4ade5779")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }

            /// <summary>
            /// The Fermer item.
            /// </summary>
            [RepositoryItem("75816664-dbdc-469a-9066-48c9327fb5b8")]
            public virtual Ranorex.Button Fermer
            {
                get
                {
                    return _fermerInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Fermer item info.
            /// </summary>
            [RepositoryItemInfo("75816664-dbdc-469a-9066-48c9327fb5b8")]
            public virtual RepoItemInfo FermerInfo
            {
                get
                {
                    return _fermerInfo;
                }
            }
        }

        /// <summary>
        /// The SettingsOcm2AppFolder folder.
        /// </summary>
        [RepositoryFolder("413a49aa-6c53-4413-9db1-89591d113649")]
        public partial class SettingsOcm2AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _impressionInfo;
            RepoItemInfo _configurationInfo;
            RepoItemInfo _quitterInfo;

            /// <summary>
            /// Creates a new SettingsOcm2  folder.
            /// </summary>
            public SettingsOcm2AppFolder(RepoGenBaseFolder parentFolder) :
                    base("SettingsOcm2", "/contextmenu[@processname='SettingsOcm 2']", parentFolder, 30000, null, false, "413a49aa-6c53-4413-9db1-89591d113649", "")
            {
                _impressionInfo = new RepoItemInfo(this, "Impression", "?/?/menuitem[@accessiblename='Impression...']", "?/?/menuitem[@accessiblename='Impression...']", 30000, null, "eca889da-05bb-45c7-89a8-d97dbbda6642");
                _configurationInfo = new RepoItemInfo(this, "Configuration", "?/?/menuitem[@accessiblename='Configuration...']", "?/?/menuitem[@accessiblename='Configuration...']", 30000, null, "be9ffaaa-4150-4e33-8f52-55965fd61fdc");
                _quitterInfo = new RepoItemInfo(this, "Quitter", "?/?/menuitem[@accessiblename='Quitter']", "?/?/menuitem[@accessiblename='Quitter']", 30000, null, "1f1d4e60-96f4-498a-a8ab-fc4fe3555e0c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("413a49aa-6c53-4413-9db1-89591d113649")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("413a49aa-6c53-4413-9db1-89591d113649")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Impression item.
            /// </summary>
            [RepositoryItem("eca889da-05bb-45c7-89a8-d97dbbda6642")]
            public virtual Ranorex.MenuItem Impression
            {
                get
                {
                    return _impressionInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Impression item info.
            /// </summary>
            [RepositoryItemInfo("eca889da-05bb-45c7-89a8-d97dbbda6642")]
            public virtual RepoItemInfo ImpressionInfo
            {
                get
                {
                    return _impressionInfo;
                }
            }

            /// <summary>
            /// The Configuration item.
            /// </summary>
            [RepositoryItem("be9ffaaa-4150-4e33-8f52-55965fd61fdc")]
            public virtual Ranorex.MenuItem Configuration
            {
                get
                {
                    return _configurationInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Configuration item info.
            /// </summary>
            [RepositoryItemInfo("be9ffaaa-4150-4e33-8f52-55965fd61fdc")]
            public virtual RepoItemInfo ConfigurationInfo
            {
                get
                {
                    return _configurationInfo;
                }
            }

            /// <summary>
            /// The Quitter item.
            /// </summary>
            [RepositoryItem("1f1d4e60-96f4-498a-a8ab-fc4fe3555e0c")]
            public virtual Ranorex.MenuItem Quitter
            {
                get
                {
                    return _quitterInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Quitter item info.
            /// </summary>
            [RepositoryItemInfo("1f1d4e60-96f4-498a-a8ab-fc4fe3555e0c")]
            public virtual RepoItemInfo QuitterInfo
            {
                get
                {
                    return _quitterInfo;
                }
            }
        }

        /// <summary>
        /// The ConfirmerAppFolder folder.
        /// </summary>
        [RepositoryFolder("565f90a0-7a69-4c4f-9839-43e45070cb92")]
        public partial class ConfirmerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonouiInfo;

            /// <summary>
            /// Creates a new Confirmer  folder.
            /// </summary>
            public ConfirmerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Confirmer", "/form[@name='none']", parentFolder, 30000, null, true, "565f90a0-7a69-4c4f-9839-43e45070cb92", "")
            {
                _buttonouiInfo = new RepoItemInfo(this, "ButtonOui", "button[@name='Yes']", "button[@name='Yes']", 30000, null, "e9a21543-891f-4f59-9c65-1b176f079106");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("565f90a0-7a69-4c4f-9839-43e45070cb92")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("565f90a0-7a69-4c4f-9839-43e45070cb92")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonOui item.
            /// </summary>
            [RepositoryItem("e9a21543-891f-4f59-9c65-1b176f079106")]
            public virtual Ranorex.Button ButtonOui
            {
                get
                {
                    return _buttonouiInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOui item info.
            /// </summary>
            [RepositoryItemInfo("e9a21543-891f-4f59-9c65-1b176f079106")]
            public virtual RepoItemInfo ButtonOuiInfo
            {
                get
                {
                    return _buttonouiInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
