///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;
using System.Data.SqlClient;

namespace Demo01
{
    public partial class Recording1
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public string getDataFromDB()
        {
            // TODO: Replace the following line with your code implementation.
            Report.Log(ReportLevel.Info, "Mouse", "Getting data from DB");
//            String test1 = "77";
//            if (test1 == "77"){
//            	Report.Log(ReportLevel.Info, "Mouse", "EQUAL 77");
//            	throw new NotImplementedException();
//            	
//            }else{
//            	Report.Log(ReportLevel.Info, "Mouse", "NOT EQUAL 77");
//            	throw new NotImplementedException();
//            }
//            Report.Log(ReportLevel.Info, "Mouse", "Getting data from DB ${test1});
            string connetionString;
   SqlConnection cnn;
   connetionString = @"Data Source=qa-automat01.lab.ncelab;Initial Catalog=Protect;User ID=sa;Password=B@lly!01";
   cnn = new SqlConnection(connetionString);
   cnn.Open();
   SqlCommand command;
   SqlDataReader dataReader;
   String sql, Output="";
   sql = "select top 10* from mouchard order by 2 desc";
   command = new SqlCommand(sql, cnn);
   dataReader = command.ExecuteReader();
   while (dataReader.Read())
   {
   	Output = Output + dataReader.GetValue(0) + " - " + dataReader.GetValue(1) + " - " + dataReader.GetValue(3) + " - " + dataReader.GetValue(6) + " ************* " + "\n";
   }
   
   
   
   Report.Log(ReportLevel.Info, "Mouse", "Got "+Output);
   
   
   
//   SqlCommand sqlComm = new SqlCommand();
//   sqlComm.CommandText = "select top 10* from mouchard order by 2 desc";
//   object result = sqlComm.ExecuteScalar();
//   Report.Log(ReportLevel.Info, "Mouse", "Connected to the DB = ", result.ToString);
   cnn.Close();
            
            
            
//            throw new NotImplementedException();
            return null;
        }

        public void Validate_ButtonOui(RepoItemInfo buttonInfo)
        {
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual ((Choose)='aaaa') on item 'buttonInfo'.", buttonInfo);
            Validate.AttributeEqual(buttonInfo, "(Choose)", "aaaabbbb");
        }

    }
}
